@id = 5d7fd4f92ec4e7917bc4c4a0
DELETE http://localhost:3003/api/blogs/{{id}}
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVseXNldyIsImlkIjoiNWQ3ZmQwN2MyZWM0ZTc5MTdiYzRjNDliIiwiaWF0IjoxNTY4NjU4NjY0fQ.YwVCLqrYROsIM8K_IzUGHskw8ZMDBoCZiF3ffCEUJUk